<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
   public function getByAuteurAndNom($auteur, $nom)
   {
      return $this->createQueryBuilder('a') /// a est un alias
      ->select('a')
      ->where('a.nom = :nom AND a.auteur = :auteur')
      ->setParameter('nom', $nom)
      ->setParameter('auteur', $auteur)
      ->getQuery()
      ->getResult();
   }
}
