app_contact:
    resource: "@AppBundle/Resources/config/routing/contact.yml"
    prefix:   /admin/contact

homepage:
    path: /
    defaults: { _controller: 'AppBundle:Default:index'}

contact:
    path: /contact
    defaults: { _controller: 'AppBundle:Default:contact'}

